const FIREBASE_ENV_KEYS = [
  "NEXT_PUBLIC_FIREBASE_API_KEY",
  "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",
  "NEXT_PUBLIC_FIREBASE_PROJECT_ID",
  "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",
  "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",
  "NEXT_PUBLIC_FIREBASE_APP_ID",
] as const;

function quoteEnvValue(value: string) {
  return JSON.stringify(value);
}

export function GET() {
  const missing = FIREBASE_ENV_KEYS.filter((key) => !process.env[key]);
  if (missing.length) {
    return new Response(`Missing Firebase env values: ${missing.join(", ")}\n`, {
      status: 500,
      headers: {
        "content-type": "text/plain; charset=utf-8",
      },
    });
  }

  const body = [
    "# Generated by agent-usage-tracker.",
    "# Firebase Web App config is public client configuration.",
    ...FIREBASE_ENV_KEYS.map((key) => `${key}=${quoteEnvValue(process.env[key] ?? "")}`),
    "",
  ].join("\n");

  return new Response(body, {
    headers: {
      "cache-control": "no-store",
      "content-type": "text/plain; charset=utf-8",
    },
  });
}
